name: Python Script

on:
  workflow_dispatch:
    inputs:
      STR_TO_REPLACE:
        description: 'String to replace'
        required: true
        default: '-this-one-officer'
      REPLACEMENT_STRING:
        description: 'Replacement string'
        required: true
        default: 'arrested'
      REPOS_TO_CHANGE:
        description: 'Repositories to change (comma-separated)'
        required: false
        default: ''
      EXCLUDED_REPOS:
        description: 'Repositories to exclude (comma-separated)'
        required: false
        default: 'Repo2'
      NAME_SPACE:
        description: 'Namespace(s) (comma-separated)'
        required: false
        default: 'finance'
      FILE_EXCLUSIONS:
        description: 'Files to exclude (comma-separated)'
        required: false
        default: 'build.gradle'
      CHANGE_REPO_NAME:
        description: 'Change repository name (true/false)'
        required: true
        default: 'true'

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install PyYaml
      run: pip install pyyaml # If you have dependencies, install them from requirements.txt

    - name: Run Python script
      env:
        GITHUB_TOKEN: ${{ secrets.BULK_TOKEN }}  # Use the built-in GitHub token secret
        STR_TO_REPLACE: ${{ github.event.inputs.STR_TO_REPLACE }}
        REPLACEMENT_STRING: ${{ github.event.inputs.REPLACEMENT_STRING }}
        REPOS_TO_CHANGE: ${{ github.event.inputs.REPOS_TO_CHANGE }}
        EXCLUDED_REPOS: ${{ github.event.inputs.EXCLUDED_REPOS }}
        NAME_SPACE: ${{ github.event.inputs.NAME_SPACE }}
        FILE_EXCLUSIONS: ${{ github.event.inputs.FILE_EXCLUSIONS }}
        CHANGE_REPO_NAME: ${{ github.event.inputs.CHANGE_REPO_NAME }}
      run: python RepoEdit.py  # Replace with the name of your Python script
